version: "2.0"

services:
  mysql:
    container_name: start-spring-boot-mysql
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./.volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci  --log-bin-trust-function-creators=1
    environment:
      - MYSQL_ROOT_PASSWORD=jpa
      - MYSQL_DATABASE=jpa_ex
      - MYSQL_USER=jpa
      - MYSQL_PASSWORD=jpa
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
