version: '3.7'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: prisma-example.mysql
            port: 3306
            user: root
            password: user
            migrations: true

  mysql:
    container_name: prisma-example.mysql
    image: mysql:5.7.31
    ports:
      - 3306:3306
    volumes:
      - ./volume/prisma-example.mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --log-bin-trust-function-creators=1
    environment:
      - MYSQL_ROOT_PASSWORD=user
      - MYSQL_DATABASE=prisma-example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    restart: always
